# Test Case
# Step 1: Create new game
# Step 2: Move blue pawn from Bd2 to Bd4
# Step 3: Move green pawn from Gb2 to Gb3
# Step 4: Create new game
# Expected: Start position with a blue pawn on Bd2 and green pawn on  Gb2

### Step1: Create new game
GET http://localhost:8080/newGame

### Step2a: Click Square Bd2
POST http://localhost:8080/move
Content-Type: text/plain

Bd2

### Step2b: Click Square Bd4
POST http://localhost:8080/move
Content-Type: text/plain

Bd4

### Step3a: Click Square Gb2
POST http://localhost:8080/move
Content-Type: text/plain

Gb2

### Step3b: Click Square Gb3
POST http://localhost:8080/move
Content-Type: text/plain

Bb3

### Step4: Create new game
GET http://localhost:8080/newGame

### Test expected beahvior: board with starting position
GET http://localhost:8080/board

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Response content-type is json", function() {
        let type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });

    client.test("Blue pawn on Bd2", function() {
        client.assert(response.body['Bd2'] == 'BP', "No blue pawn on Bd2");
    });

    client.test("Green pawn on Gb2", function() {
        client.assert(response.body['Gb2'] == 'GP', "No green pawn on Gb2");
    });
%}